server:
  port: ${SERVICE_PORT:8080}
  shutdown: graceful
spring:
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false
logging:
  file:
    name: application.main.log
  spring:
  datasource:
    url:jdbc:h2:mem: testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  springdoc:
    api-docs:
      path: /v1/api
    swagger-ui:
      path: /documentation.html